/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fmr;

import dao.rl_caje_admin;
import dao.rl_usuario;
import florma.usuario;

/**
 *
 * @author elcar
 */
public class RegistroCajeAdmin extends javax.swing.JFrame {
usuario uss;

    public void AbsUser(usuario c) {
        this.uss = c;
        //txtCaje.setText(c.getApellidoPaterno()+" "+c.getApellidoMaterno()+" "+c.getNombres());
    }
    
    public RegistroCajeAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnGuardarCA = new javax.swing.JButton();
        cbR = new javax.swing.JComboBox<>();
        entryC = new javax.swing.JTextField();
        entryD = new javax.swing.JTextField();
        entryAP = new javax.swing.JTextField();
        entryAM = new javax.swing.JTextField();
        entryN = new javax.swing.JTextField();
        entryT = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        entryci = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        entryCO = new javax.swing.JTextField();
        entryU = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro De Cajero Administrador");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 0, 680, 51));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cedula");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido Paterno");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Apellido  Materno");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombres");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Rol");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 40, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Direccion");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Telefono");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Correo");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));

        btnGuardarCA.setBackground(new java.awt.Color(159, 111, 145));
        btnGuardarCA.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardarCA.setText("Guardar");
        btnGuardarCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCAActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarCA, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 464, 373, 43));

        cbR.setBackground(new java.awt.Color(255, 204, 255));
        cbR.setForeground(new java.awt.Color(0, 0, 0));
        cbR.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cajero", "Administrador" }));
        jPanel1.add(cbR, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        entryC.setBackground(new java.awt.Color(255, 204, 255));
        entryC.setBorder(null);
        jPanel1.add(entryC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 270, 30));

        entryD.setBackground(new java.awt.Color(255, 204, 255));
        entryD.setBorder(null);
        jPanel1.add(entryD, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 270, 30));

        entryAP.setBackground(new java.awt.Color(255, 204, 255));
        entryAP.setBorder(null);
        jPanel1.add(entryAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 270, 30));

        entryAM.setBackground(new java.awt.Color(255, 204, 255));
        entryAM.setBorder(null);
        jPanel1.add(entryAM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 270, 30));

        entryN.setBackground(new java.awt.Color(255, 204, 255));
        entryN.setBorder(null);
        entryN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNActionPerformed(evt);
            }
        });
        jPanel1.add(entryN, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 270, 30));

        entryT.setBackground(new java.awt.Color(255, 204, 255));
        entryT.setBorder(null);
        entryT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryTActionPerformed(evt);
            }
        });
        jPanel1.add(entryT, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 270, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 270, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 270, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 270, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 270, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 270, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 270, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 270, 10));

        entryci.setBackground(new java.awt.Color(255, 204, 255));
        entryci.setBorder(null);
        jPanel1.add(entryci, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 270, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 51));
        jLabel10.setText("X");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setFocusable(false);
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 20, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Usuario");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Contraseña");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        entryCO.setBackground(new java.awt.Color(255, 204, 255));
        entryCO.setBorder(null);
        jPanel1.add(entryCO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 400, 270, 30));

        entryU.setBackground(new java.awt.Color(255, 204, 255));
        entryU.setBorder(null);
        jPanel1.add(entryU, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 270, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 270, 10));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 270, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCAActionPerformed
        usuario u= new usuario();
         rl_usuario d = new rl_usuario();
        rl_caje_admin g = new rl_caje_admin();
        u.setCi(entryci.getText());
        u.setApellidoPaterno(entryAP.getText());
        u.setApellidoMaterno(entryAM.getText());
        u.setNombres(entryN.getText());
        u.setRol(cbR.getSelectedIndex()+3);
        u.setDireccion(entryD.getText());
        u.setTelefono(entryT.getText());
        u.setCorreo(entryC.getText());
        d.guardarUsuario(u);
        System.out.println(u.getRol());
        
        int ur = g.obtenerIdUsuarioRecienGuardada();
        g.guardarCajeAdmin(entryU.getText(),entryCO.getText(),ur);
        
        
        
    }//GEN-LAST:event_btnGuardarCAActionPerformed

    private void entryNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNActionPerformed

    private void entryTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryTActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
           this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarCA;
    private javax.swing.JComboBox<String> cbR;
    private javax.swing.JTextField entryAM;
    private javax.swing.JTextField entryAP;
    private javax.swing.JTextField entryC;
    private javax.swing.JTextField entryCO;
    private javax.swing.JTextField entryD;
    private javax.swing.JTextField entryN;
    private javax.swing.JTextField entryT;
    private javax.swing.JTextField entryU;
    private javax.swing.JTextField entryci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
